# Use the official DragonflyDB image as the base
FROM docker.dragonflydb.io/dragonflydb/dragonfly

# Expose the default DragonflyDB port
EXPOSE 6379

# Create data directory
RUN mkdir -p /data

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint script as the command to run
ENTRYPOINT ["/entrypoint.sh"]
